<script src="{{asset('backend/other/jss/jquery-3.6.1.min.js')}}"></script>
<script src="{{asset('backend/other/jss/owl.carousel.min.js')}}"></script>
<script src="{{asset('backend/other/jss/bootstrap.js')}}"></script>
<script src="{{asset('backend/other/jss/counterup/jquery.counterup.min.js')}}"></script>
<script src="{{asset('backend/other/jss/waypoint/jquery.waypoints.js')}}"></script>
<script src="{{asset('backend/other/jss/wow/wow.min.js')}}"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.2.1/dist/chart.umd.min.js"
        integrity="sha384-gdQErvCNWvHQZj6XZM0dNsAoY4v+j5P1XDpNkcM3HJG1Yx04ecqIHk7+4VBOCHOG"
        crossorigin="anonymous"></script>
<script src="{{asset('backend/other/jss/script.js')}}"></script>
